Dear {{first_name}},
<br /><br />
A new document has been added to your Crownfire account.  You can now access this report 24 hours a day, 7 days a week.
<br /><br />
<b>Document Information</b>
<br /> <br />
<table width="50%">
 <tr bgcolor="#EEEEEE">
  <td><b>Address</b></td>
  <td><b>Document Type</b></td>
  <td>&nbsp; </td>
 </tr>
 <tr valign="top">
  <td>{{property_address}}</td>
  <td>{{document_type}}</td>
  <td align="center"><a href="http://www.crownfire.ca/members/view_document.php?id={{document_id}}">View Report</a></td>
 </tr>
</table>
<br />

<b>Login Information</b><br /><br />
<table>
 <tr>
  <td>Your username:</td>
  <td>{{username}}</td>
 </tr>
 <tr>
  <td>Your password:</td>
  <td>{{password}}</td>
 </tr> 
</table>
<br />

Thank you<br /><br />
<b>Crownfire Equiptment</b>