Dear {{first_name}},
<br /><br />
Your Crownfire reports are available on demand from our website.  You can find us online at
<br /><br />
<a href="http://www.crownfire.ca">http://www.crownfire.ca</a>.
<br /><br />
<table>
 <tr>
  <td>Your username:</td>
  <td>{{username}}</td>
 </tr>
 <tr>
  <td>Your password:</td>
  <td>{{password}}</td>
 </tr> 
</table>
<br />

Thank you<br /><br />
<b>Crownfire Equiptment</b>